version: '3.7'
services:
#  web:
#    build:
#      context: ./web
#      dockerfile: ProdDockerfile
#    ports:
#      - 80:80
#    environment:
#      - API_URL=http://127.0.0.1:8002/
#    depends_on:
#      - embedding_api
  embedding_api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8008:8008"