version: '3.7'
services:
  web:
    build: ./web
    volumes:
      - type: bind
        source: ./web/src
        target: /app/src
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://127.0.0.1:8008/
    depends_on:
      - embedding_api
  embedding_api:
    build: api/.
    ports:
      - "8008:8008"