version: "3.8"
services:
  notebooks:
    build: ./app
    ports:
      - "8001:8888"
    volumes:
      - type: bind
        source: ./app
        target: /home/jovyan/work
      - type: bind
        source: ./data
        target: /home/jovyan/data

  embedding_api:
    build: application/api/.
    command: [uvicorn, app.main:app, --port, "8002"]
    network_mode: host
    ports:
      - "8002:8002"