apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: embedding-api
  name: embedding-api
spec:
  ports:
  - name: "8002"
    port: 8002
    targetPort: 8002
  selector:
    io.kompose.service: embedding-api
status:
  loadBalancer: {}
